### ISSUE TITLE
Cannot Install Plugin on Self-Hosted Discourse server - rbsecp256k1

### ISSUE THREAD

**Issue by Sterahi** [spruceid/discourse-siwe-auth#15] opened 2022-05-20 17:01 UTC
Using the latest docker image from Discourse we're seeing the error: 
```
I, [2022-05-20T16:58:42.288275 #1]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
ERROR:  Error installing rbsecp256k1:
	ERROR: Failed to build gem native extension.

    current directory: /var/www/discourse/plugins/discourse-siwe-auth/gems/2.7.6/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r ./siteconf20220520-1530-cv5chg.rb extconf.rb
Downloading libsecp256k1.zip (100%)
```
Even after installing the required system-level dependencies of rbsecp256k1 our discourse server will not start. Our app.yml looks like: 

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/spruceid/discourse-siwe-auth.git
```

Any assistance would be appreciated!

**Comment by obstropolos** [comment] 2022-05-31 18:08
> Just an update, after re-testing today I can confirm that the changes made [here](https://github.com/discourse/discourse/pull/16176) did not resolve the issue we're having.

Thanks for the heads up - we're looking into this.

**Comment by miguelmota** [comment] 2022-06-14 04:33
Hi, is there any update on this issue?

![DeepinScreenshot_select-area_20220613213153](https://user-images.githubusercontent.com/168240/173493798-44c44095-754b-4451-b1a7-47a205a7e589.png)

**Comment by burningtree** [comment] 2022-06-18 08:34
I have the same problem:
```
ERROR:  Error installing rbsecp256k1:
	ERROR: Failed to build gem native extension.
```

Im using:
- Ubuntu 22.04 LTS
- Docker version 20.10.17

**Comment by zashton** [comment] 2022-06-27 13:37
> > Just an update, after re-testing today I can confirm that the changes made [here](https://github.com/discourse/discourse/pull/16176) did not resolve the issue we're having.
> 
> Thanks for the heads up - we're looking into this.

any luck on this issue ? 
trying for the first time on a fresh installation of discourse and couldn't install the plugin at all

**Comment by obstropolos** [comment] 2022-06-27 16:51
Still trying to find the root cause here, thanks again for your patience all -

**Comment by communiteq** [comment] 2022-07-03 18:21
All you need to do is add the `before_code `lines to app.yml to make sure the rubyzip gem is installed.
I don't know how to fix this _within_ the plugin though.

```
hooks:
  before_code:
    - exec:
        cmd:
          - gem install rubyzip
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/spruceid/discourse-siwe-auth
```

**Comment by w4ll3** [comment] 2022-07-07 15:46
@Sterahi Sorry for the delay on this. I can confirm that the solution above solves the issue (at least did for me), could you give it a try and confirm that solves for you as well?

@communiteq Thanks for your contribution.

**Comment by obstropolos** [comment] 2022-07-07 20:08
> All you need to do is add the `before_code `lines to app.yml to make sure the rubyzip gem is installed. I don't know how to fix this _within_ the plugin though.
> 
> ```
> hooks:
>   before_code:
>     - exec:
>         cmd:
>           - gem install rubyzip
>   after_code:
>     - exec:
>         cd: $home/plugins
>         cmd:
>           - git clone https://github.com/discourse/docker_manager.git
>           - git clone https://github.com/spruceid/discourse-siwe-auth
> ```

Echoing @w4ll3 - thanks for the contribution here. We'll update the documentation to reflect these changes [#17] and we'll close the issue out once we have some confirmation from other folks affected.

I just rebuilt a fresh discourse instance on a new server using this fix and it all worked.

**Comment by miguelmota** [comment] 2022-07-08 06:21
The suggestion by @communiteq worked great on an existing instance!

**Comment by obstropolos** [comment] 2022-07-11 15:52
Closing this issue for now with the latest suggestion and changes. 

Will reopen if persists with projects.

**Closed by obstropolos** 2022-07-11 15:52 UTC
Labels: siwe-discourse

**Comment by joshuniverse** [comment] 2025-02-11 03:07
Pups::ExecError: cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate' failed with return #<Process::Status: pid 777 exit 1>
Location of failure: /usr/local/lib/ruby/gems/3.3.0/gems/pups-1.2.1/lib/pups/exec_command.rb:132:in `spawn'
exec failed with the params {"cd"=>"$home", "tag"=>"migrate", "hook"=>"db_migrate", "cmd"=>["su discourse -c 'bundle exec rake db:migrate'"]}
bootstrap failed with exit code 1
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one.
./discourse-doctor may help diagnose the problem.
